# Core PLL outputs are used as separate clock domains.
# The system SDC groups them together because they come from the same PLL, so
# explicitly declare them asynchronous to match the renderer CDC structure:
#   clk_50   sound (POKEY and the analog section)
#   clk_12   CPU, address decode, mathbox, AVG
#   clk_125  renderer, DDRAM, SDRAM, video readout
#
# clk_6 is generated by the PLL but unused, so the fitter removes its output
# counter and get_clocks returns nothing for it. Build the group list from the
# clocks that actually exist so the constraint does not depend on that.

set emu_groups {}
foreach idx {0 1 2 3} {
	set c [get_clocks -nowarn \
		"emu|pll|pll_inst|altera_pll_i|general\[$idx\].gpll~PLL_OUTPUT_COUNTER|divclk"]
	if {[get_collection_size $c] > 0} {
		lappend emu_groups -group
		lappend emu_groups $c
	}
}

if {[llength $emu_groups] > 2} {
	eval set_clock_groups -asynchronous $emu_groups
}

# The renderer's OSD control registers (vfb_top.sv:417-440) are the tail of a
# CDC synchronizer chain carrying menu settings into the video domain. They are
# static for millions of cycles and only move when the user changes an OSD
# option, so the several-hundred-picosecond setup failures reported on the paths
# out of them into the bloom filter are not data-path violations. Relax them
# rather than let quasi-static configuration dominate the timing report.
set osd_cfg [get_registers -nowarn {*vfb_top*osd_*_vid*}]
set osd_cfg2 [get_registers -nowarn {*vfb_top*bloom_curve_gain*}]
set osd_cfg3 [get_registers -nowarn {*vfb_top*halo_filter*}]

foreach c [list $osd_cfg $osd_cfg2 $osd_cfg3] {
	if {[get_collection_size $c] > 0} {
		set_multicycle_path -setup -from $c 4
		set_multicycle_path -hold  -from $c 3
	}
}
