# Core PLL outputs are used as separate clock domains.
# The system SDC groups them together because they come from the same PLL, so
# explicitly declare them asynchronous to match the renderer CDC structure:
#   clk_50   sound (POKEY and the analog section)
#   clk_12   CPU, address decode, mathbox, AVG
#   clk_125  renderer, DDRAM, SDRAM, video readout
#
# clk_6 is generated by the PLL but unused, so the fitter removes its output
# counter and get_clocks returns nothing for it. Build the group list from the
# clocks that actually exist so the constraint does not depend on that.

set emu_groups {}
foreach idx {0 1 2 3} {
	set c [get_clocks -nowarn \
		"emu|pll|pll_inst|altera_pll_i|general\[$idx\].gpll~PLL_OUTPUT_COUNTER|divclk"]
	if {[get_collection_size $c] > 0} {
		lappend emu_groups -group
		lappend emu_groups $c
	}
}

if {[llength $emu_groups] > 2} {
	eval set_clock_groups -asynchronous $emu_groups
}
